config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

class Comment < ActiveRecord::Base
  validates :content,
            :post_id,
            :user_id,
            presence: true

  #TODO Prevent obscene comments from 'bad actors' aka trolls.

  belongs_to :post

  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

class Post < ActiveRecord::Base
  validates :title,
            :content,
            :user_id,
            presence: true

  #TODO Consider adding validation for post titles being unique? Re-Post factor

  has_many :comments, :dependent => :destroy

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :encrypted_password,
            :sign_in_count,
            presence: true

  has_many :posts

  has_many :comments,
            through: :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #use devise for authenticating before all site actions
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :select_comment, only: [:edit, :update, :show, :destroy]
  before_action :ensure_comment_modification_security, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  #TODO consider refactoring to use #render instead of #redirect_to
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id

    @post = Post.find(params[:post_id])

    #TODO consider refactoring to use #render instead of #redirect_to
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to(@comment.post)
    else
      flash[:notice] = "Error creating comment: #{@comment.errors.full_messages}"
      redirect_to(@post)
    end
  end

  def show

  end

  def edit
    @post = Post.find(@comment.post_id)
  end

  #TODO consider refactoring to use #render instead of #redirect_to
  def update
    @comment.update_attributes(comment_params)
    @post = @comment.post

    if @comment.save
      flash[:notice] = 'Comment was successfully edited.'
      redirect_to(@comment.post)
    else
      flash[:notice] = "Error modifying comment: #{@comment.errors.full_messages}"
      redirect_to(@post)
    end
  end

  def destroy
    @comment.destroy

    redirect_to(@comment.post)
  end

  private
  def select_comment
    @comment = Comment.find(params[:id])
  end

  #TODO consider refactoring to use #render instead of #redirect_to
  def ensure_comment_modification_security
    unless @comment.user_id == current_user.id
      flash[:notice] = "Only a comment's creator can edit or delete it"
      redirect_to(@comment.post)
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :select_post, only: [:edit, :update, :show, :destroy]
  before_action :ensure_post_modification_security, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  #TODO consider refactoring to use #render instead of #redirect_to
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to(@post)
    else
      flash[:notice] = "Error creating post: #{@post.errors.full_messages}"
      redirect_to(@post)
    end
  end

  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def edit

  end

  ##TODO consider refactoring to use #render instead of #redirect_to
  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully edited.'
      redirect_to(@post)
    else
      flash[:notice] = "Error modifying post: #{@post.errors.full_messages}"
      redirect_to(@post)
    end
  end

  def destroy
    @post.destroy
    redirect_to(@post)
  end

  private
  def select_post
    @post = Post.find(params[:id])
  end

  #TODO consider refactoring to use #render instead of #redirect_to
  def ensure_post_modification_security
    unless @post.user_id == current_user.id
      flash[:notice] = "Only a post's creator can edit or delete it"
      redirect_to(@post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @post, @comment ] do |a| %>
  <p>
    <%= a.label :content %><br/>
    <%= a.text_area :content %>
  </p>
  <p>
    <%= a.submit 'Submit' %>
  </p>
<% end %>

app/views/comments/_new.html.erb
<h3>Post a Comment</h3>

<%= render partial: 'form' %>

app/views/comments/_show.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @post, @comment ] do |a| %>
  <p>
    <%= a.label :content %><br/>
    <%= a.text_area :content %>
  </p>
  <p>
    <%= a.submit 'Submit' %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h3>Post a Comment</h3>

<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Basic Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <% if user_signed_in? %>
    <section>
      Welcome <%=current_user.email%>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </section>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  <%= yield %>

</body>

</html>

app/views/posts/_comment.html.erb
<div>
  <h4>Comment by <%= comment.user.email %></h4>
  <p class="comment"><%= comment.content %></p>
  <p><%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> after post</p>

  <%= link_to "delete comment", post_comment_path(@post, comment), method: :delete,
      data: {confirm: "Really delete the comment?"}
  %>
  <br>
  <%= link_to "edit", edit_post_comment_path(@post, comment) %>
  <br>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |post| %>
  <ul>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= post.label :title %><br />
    <%= post.text_field :title %>
  </p>

  <p>
    <%= post.label :content %><br />
    <%= post.text_area :content %>
  </p>
  <p>
    <%= post.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>

  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.content %></td>
      </tr>
    <% end %>
  </tbody>


</table>
<br>
<%= link_to "Create a New Post", new_post_path, class: "new_post" %>
<br>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

<%= form_for(@post) do |post| %>
  <ul>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= post.label :title %><br />
    <%= post.text_field :title %>
  </p>

  <p>
    <%= post.label :content %><br />
    <%= post.text_area :content %>
  </p>
  <p>
    <%= post.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<%= link_to "delete post", post_path(@post), method: :delete,
    data: {confirm: "Really delete the post?"}
%>
<br>
<%= link_to "edit", edit_post_path(@post) %>
<br>

<h3>Comments (<%= @post.comments.size %>) </h3>
<%= render partial: 'posts/comment', collection: @post.comments.includes(:user) %>

<%= render partial: 'comments/show' %>

<br>
<%= link_to "<< Back to Post List", posts_path %>